package de.groupchat.core;

import com.electronwill.nightconfig.toml.TomlParser;
import com.google.gson.JsonParser;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.AtomicMoveNotSupportedException;

public record GcConfig(long inviteCooldownSeconds, int maxOwnedGroups, long inviteExpiryDays, long chatLogRetentionHours) {
    public static final String LOG_SETTING = """
            # Group message retention in groupchats/logs, in hours.
            # Expired entries are removed at startup and about once a minute.
            chat_log_retention_hours = 24
            """;
    public static final String DEFAULT_TOML = """
            # GroupChat - Changes take effect after restarting the server.
            # Delay between invitations from the same sender to the same player.
            # Applies across all groups. Set to 0 to disable the cooldown.
            invite_cooldown_seconds = 60

            # Maximum groups owned per player. Memberships and co-owner roles do not count.
            max_owned_groups = 3

            # Invitation lifetime in days, including time the player spends offline.
            invite_expiry_days = 7
            """ + "\n" + LOG_SETTING;

    public GcConfig(long inviteCooldownSeconds, int maxOwnedGroups, long inviteExpiryDays) {
        this(inviteCooldownSeconds, maxOwnedGroups, inviteExpiryDays, 24);
    }

    public GcConfig {
        if (inviteCooldownSeconds < 0 || inviteCooldownSeconds > 31_536_000)
            throw new IllegalArgumentException("invite_cooldown_seconds must be between 0 and 31536000.");
        if (maxOwnedGroups < 1 || maxOwnedGroups > 100_000)
            throw new IllegalArgumentException("max_owned_groups must be between 1 and 100000.");
        if (inviteExpiryDays < 1 || inviteExpiryDays > 3650)
            throw new IllegalArgumentException("invite_expiry_days must be between 1 and 3650.");
        if (chatLogRetentionHours < 1 || chatLogRetentionHours > 87_600)
            throw new IllegalArgumentException("chat_log_retention_hours must be between 1 and 87600.");
    }

    public static GcConfig loadFromConfigDirectory(Path configDirectory) throws IOException {
        Path file = configDirectory.resolve("groupchats/groupchat.toml");
        Path legacy = configDirectory.resolve("groupchat.toml");
        if (Files.notExists(file) && Files.exists(legacy)) {
            parse(Files.readString(legacy)); // An invalid legacy file stays in its original location.
            Files.createDirectories(file.getParent());
            Files.move(legacy, file);
        }
        return load(file);
    }

    public static GcConfig load(Path file) throws IOException {
        Files.createDirectories(file.toAbsolutePath().getParent());
        if (Files.notExists(file)) Files.writeString(file, DEFAULT_TOML);
        String text = Files.readString(file);
        GcConfig config = parse(text);
        String updated = translateDefaultComments(text);
        if (!new TomlParser().parse(text).contains("chat_log_retention_hours")) {
            // Prepend so the setting remains at TOML root level even if user tables follow.
            updated = LOG_SETTING + "\n" + updated;
        }
        if (!updated.equals(text)) {
            Path temporary = Files.createTempFile(file.toAbsolutePath().getParent(), "groupchat-config-", ".tmp");
            try {
                Files.writeString(temporary, updated);
                try { Files.move(temporary, file, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING); }
                catch (AtomicMoveNotSupportedException e) { Files.move(temporary, file, StandardCopyOption.REPLACE_EXISTING); }
            } finally { Files.deleteIfExists(temporary); }
        }
        return config;
    }

    private static String translateDefaultComments(String text) throws IOException {
        // Only replace comments generated by earlier releases; preserve custom comments and values.
        try (var stream = GcConfig.class.getResourceAsStream("/legacy-config-comments.json")) {
            if (stream == null) throw new IOException("Missing configuration migration resource.");
            var translations = JsonParser.parseReader(new InputStreamReader(stream, StandardCharsets.UTF_8)).getAsJsonObject();
            String[] lines = text.split("\n", -1);
            for (int i = 0; i < lines.length; i++) {
                var translation = translations.get(lines[i].strip());
                if (translation != null) {
                    String indent = lines[i].substring(0, lines[i].indexOf('#'));
                    lines[i] = indent + translation.getAsString() + (lines[i].endsWith("\r") ? "\r" : "");
                }
            }
            return String.join("\n", lines);
        }
    }

    private static GcConfig parse(String text) {
        var parsed = new TomlParser().parse(text);
        return new GcConfig(number(parsed.getOrElse("invite_cooldown_seconds", 60), "invite_cooldown_seconds"),
                Math.toIntExact(number(parsed.getOrElse("max_owned_groups", 3), "max_owned_groups")),
                number(parsed.getOrElse("invite_expiry_days", 7), "invite_expiry_days"),
                number(parsed.getOrElse("chat_log_retention_hours", 24), "chat_log_retention_hours"));
    }

    private static long number(Object value, String key) {
        if (value instanceof Integer n) return n.longValue();
        if (value instanceof Long n) return n;
        throw new IllegalArgumentException(key + " must be an integer.");
    }
}
